package:
  name: test_python
  version: "2.7"

build:
  track_features:
    - py27
  features:
    {{ os.getenv('FEAT_COMPILER') }}

requirements:
  build:
    {{ os.getenv('REQ_COMPILER') }}
  run:
    {{ os.getenv('REQ_COMPILER') }}
