package:
  name: test_numpy
  version: "1.10.1"

build:
  track_features:
    - numpy110
  features:
    {{ os.getenv('FEAT_COMPILER') }}
    {{ os.getenv('FEAT_PYTHON') }}
    {{ os.getenv('FEAT_BLAS') }}

requirements:
  build:
    {{ os.getenv('REQ_COMPILER') }}
    {{ os.getenv('REQ_PYTHON') }}
    {{ os.getenv('REQ_BLAS') }}
  run:
    - test_msvc
    - test_python
    {{ os.getenv('REQ_BLAS') }}
