package:
  name: test_mkl
  version: "11.3"

build:
  track_features:
    - mkl11_3
  features:
    {{ os.getenv('FEAT_COMPILER') }}

requirements:
  build:
    {{ os.getenv('REQ_COMPILER') }}
  run:
    {{ os.getenv('REQ_COMPILER') }}
